name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents:      write
  packages:      write
  pull-requests: write

jobs:
  release-please:
    name: Release Please

    runs-on:
      ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - id:   release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: ruby
          package-name: consulkit
          component   : consulkit
          version-file: "lib/consulkit/version.rb"

          bump-minor-pre-major: true

  publish-gem:
    needs: release-please
    if:    needs.release-please.outputs.release_created

    name: Publish

    runs-on:
      ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  3.2
          bundler-cache: true

      - name: Build gem
        run: |
          gem build consulkit.gemspec --output=consulkit.gem

      - name: Publish gem to rubygems.org
        run: |
          gem push consulkit.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"

      - name: Publish gem to GitHub Packages
        run: |
          gem push --host "https://rubygems.pkg.github.com/$GITHUB_REPOSITORY_OWNER" consulkit.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
